import { DeadlineItem, ImportanceLevel, NoticeCategory } from '../types';

export function getImportanceBadgeStyle(importance: ImportanceLevel) {
  switch (importance) {
    case 'CRITICAL':
      return {
        badge: 'bg-red-50 text-red-800 border-red-300 font-bold',
        indicator: 'bg-red-600',
        border: 'border-l-4 border-l-red-600 border-stone-200',
        label: 'CRITICAL ACTION',
      };
    case 'HIGH':
      return {
        badge: 'bg-amber-50 text-amber-800 border-amber-300 font-semibold',
        indicator: 'bg-amber-500',
        border: 'border-l-4 border-l-amber-500 border-stone-200',
        label: 'HIGH PRIORITY',
      };
    case 'NORMAL':
      return {
        badge: 'bg-stone-100 text-stone-700 border-stone-300 font-medium',
        indicator: 'bg-stone-500',
        border: 'border-l-4 border-l-stone-400 border-stone-200',
        label: 'CAMPUS UPDATE',
      };
    case 'LOW':
      return {
        badge: 'bg-stone-50 text-stone-600 border-stone-200 font-normal',
        indicator: 'bg-stone-400',
        border: 'border-l-4 border-l-stone-300 border-stone-200',
        label: 'INFO ONLY',
      };
  }
}

export function getCategoryBadge(category: NoticeCategory) {
  switch (category) {
    case 'Exams & Fees':
      return 'bg-rose-50 text-rose-800 border-rose-200';
    case 'Placements & Internships':
      return 'bg-blue-50 text-blue-800 border-blue-200';
    case 'Academics & Classes':
      return 'bg-emerald-50 text-emerald-800 border-emerald-200';
    case 'Hostel & Mess':
      return 'bg-orange-50 text-orange-800 border-orange-200';
    case 'Scholarships & Aid':
      return 'bg-indigo-50 text-indigo-800 border-indigo-200';
    case 'Events & Clubs':
      return 'bg-purple-50 text-purple-800 border-purple-200';
    case 'General Administration':
    default:
      return 'bg-stone-100 text-stone-800 border-stone-200';
  }
}

export function formatDeadlineRelative(dateStr: string): string {
  try {
    const target = new Date(dateStr);
    if (isNaN(target.getTime())) return dateStr;
    const now = new Date('2026-09-18T01:21:00'); // current time anchor
    const diffMs = target.getTime() - now.getTime();
    const diffDays = Math.ceil(diffMs / (1000 * 60 * 60 * 24));

    if (diffDays < 0) return `${Math.abs(diffDays)} days ago (Expired)`;
    if (diffDays === 0) return 'Due Today!';
    if (diffDays === 1) return 'Due Tomorrow!';
    if (diffDays <= 7) return `In ${diffDays} days`;
    return `In ${diffDays} days (${target.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })})`;
  } catch {
    return dateStr;
  }
}

export function generateCalendarUrl(deadline: DeadlineItem, noticeTitle: string): string {
  try {
    const d = new Date(deadline.date);
    const dateStr = !isNaN(d.getTime())
      ? d.toISOString().replace(/-|:|\.\d+/g, '').slice(0, 8)
      : '20260925';

    const title = encodeURIComponent(`[Deadline] ${noticeTitle}`);
    const details = encodeURIComponent(
      `${deadline.description}\nPenalty if missed: ${deadline.penaltyIfMissed || 'None specified'}\nGenerated by CampusPulse`
    );

    return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&dates=${dateStr}/${dateStr}&details=${details}`;
  } catch {
    return '#';
  }
}
